steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$DOCKER_HUB_USERNAME --password=$$DOCKER_HUB_PASSWORD']
  secretEnv: ['DOCKER_HUB_USERNAME', 'DOCKER_HUB_PASSWORD']

# Build foo app
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$DOCKER_HUB_USERNAME/k8s-gateway-demo:${SHORT_SHA} .']
  secretEnv: ['DOCKER_HUB_USERNAME']
  dir: apps/foo-app
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$DOCKER_HUB_USERNAME/k8s-gateway-demo:${SHORT_SHA}']
  secretEnv: ['DOCKER_HUB_USERNAME']
  dir: apps/foo-app

# Render New Deployment config with new container version and commit to config-sync-app-owner repo
- name: 'gcr.io/google-samples/cloudbuild-kustomize:latest'
  id: Render New Deployment and Commit to config-sync-app-owner repo
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    git clone https://github.com/$$GITHUB_USERNAME/sp1-config-sync-app-owner && \
    cd sp1-config-sync-app-owner 
    git config user.email $$GITHUB_EMAIL
    git config user.name $$GITHUB_USERNAME 
    git remote set-url origin https://$$GITHUB_USERNAME:$$GITHUB_TOKEN@github.com/$$GITHUB_USERNAME/sp1-config-sync-app-owner.git
    cd ../config-ci-cd

    sed -i 's/__VERSION__/'"$SHORT_SHA"'/g' overlays/deployment/kustomization.yaml
    kustomize build overlays/deployment --output ../sp1-config-sync-app-owner/gateway-api-demo-app-"$SHORT_SHA".yaml

    cd ../sp1-config-sync-app-owner 

    rm README.md 
    echo "Update foo-app to version: ${SHORT_SHA}" > README.md

    git add . && \
    git commit -m "Rendered: ${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository foo-config-source - main branch 
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin main
  secretEnv: ['GITHUB_EMAIL', 'GITHUB_USERNAME', 'GITHUB_TOKEN']

# Render HTTPRoute 
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Render New HTTPRoute and Commit to config-sync-app-owner repo
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    git clone https://github.com/$$GITHUB_USERNAME/sp1-config-sync-app-owner && \
    cd sp1-config-sync-app-owner 
    git config user.email $$GITHUB_EMAIL
    git config user.name $$GITHUB_USERNAME 
    git remote set-url origin https://$$GITHUB_USERNAME:$$GITHUB_TOKEN@github.com/$$GITHUB_USERNAME/sp1-config-sync-app-owner.git
    cd ../config-ci-cd

    # Consider a better way to ensure new version of the app/service is deployed
    sleep 20 
    
    gcloud container clusters get-credentials s1p-demo --zone=us-central1-c
    export SERVICES=$(kubectl get service -n foo --sort-by=.metadata.creationTimestamp | awk '{print $1}' | tail -n +2)
    export NO_OF_SERVICES=$(echo $SERVICES | wc -l)
    if [ $NO_OF_SERVICES -eq "2" ]; 
    then 
      echo "got 2"; 
      SERVICE_N_SHA = $(echo $SERVICES | awk '{print $1}') | sed -e "s/^k8s-gateway-api-demo-service-//"
      sed -i 's/__PREVIOUS_VERSION__/'"$SERVICE_N_SHA"'/g' overlays/prod-50-50/kustomization.yaml
      SERVICE_N_PLUS_1_SHA = $(echo $SERVICES | awk '{print $2}' | sed -e "s/^k8s-gateway-api-demo-service-//")
      sed -i 's/__VERSION__/'"$SERVICE_N_PLUS_1_SHA"'/g' overlays/prod-50-50/kustomization.yaml
      kustomize build overlays/deployment --output ../sp1-config-sync-app-owner/gateway-api-demo-app-http-route.yaml

      git add . && \
      git commit -m "Rendered: ${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository foo-config-source - main branch 
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
      git request-pull 
    else 
      echo "check your services"; 
    fi
    
  secretEnv: ['GITHUB_EMAIL', 'GITHUB_USERNAME', 'GITHUB_TOKEN']


availableSecrets:
  secretManager:
  - versionName: projects/sp1-21-gateway/secrets/docker-password/versions/1
    env: 'DOCKER_HUB_PASSWORD'
  - versionName: projects/sp1-21-gateway/secrets/docker-username/versions/1
    env: 'DOCKER_HUB_USERNAME'
  - versionName: projects/${PROJECT_ID}/secrets/github-username/versions/1 
    env: 'GITHUB_USERNAME'
  - versionName: projects/${PROJECT_ID}/secrets/github-token/versions/1 
    env: 'GITHUB_TOKEN'
  - versionName: projects/${PROJECT_ID}/secrets/github-email/versions/1 
    env: 'GITHUB_EMAIL'
