 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']

# Build foo app
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/k8s-gateway-demo:${SHORT_SHA} .']
   secretEnv: ['USERNAME']
   dir: apps/foo-app
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/k8s-gateway-demo:${SHORT_SHA}']
   secretEnv: ['USERNAME']
   dir: apps/foo-app

 availableSecrets:
   secretManager:
   - versionName: projects/sp1-21-gateway/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/sp1-21-gateway/secrets/docker-username/versions/1
     env: 'USERNAME'
