steps:
# Render HTTPRoute to rollout 100% traffic to N+1
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: Rollback new application deployment and route 100% traffic to older deployment 
  entrypoint: 'bash'
  args: ['./rollout.sh']
  secretEnv: ['GITHUB_EMAIL', 'GITHUB_USERNAME', 'GITHUB_TOKEN']
  env: [_CLUSTER_NAME=$_CLUSTER_NAME, _CLUSTER_REGION=$_CLUSTER_REGION]

substitutions:
  _CLUSTER_NAME: k8s-gateway # default cluster name
  _CLUSTER_REGION: us-central1 # default cluster region

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-username/versions/latest
    env: 'GITHUB_USERNAME'
  - versionName: projects/${PROJECT_ID}/secrets/github-sp1-token/versions/latest 
    env: 'GITHUB_TOKEN'
  - versionName: projects/${PROJECT_ID}/secrets/github-email/versions/latest 
    env: 'GITHUB_EMAIL'
