kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: k8s-gateway-api-demo
  labels:
    gateway: external-http
spec:
  gateways:
    allow: All
  # hostnames:
  # - "store.example.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    forwardTo:
    - serviceName: k8s-gateway-api-demo-service-v1
      port: 8080
      weight: 100
    - serviceName: k8s-gateway-api-demo-service-v2
      port: 8080
      weight: 0