# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START anthos_config_management_multi_environments_kustomize_config_source_overlays_dev_kustomization] 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../config-ci-cd/base/foo/route

patches:
- target:
    kind: HTTPRoute
    name: k8s-gateway-api-demo
  patch: |-
    - op: replace
      path: /spec/rules/0/forwardTo/0/serviceName
      value: "k8s-gateway-api-demo-service-__VERSION__"
    - op: replace
      path: /spec/rules/0/forwardTo/0/weight
      value: 100

      # Remove second app 
    - op: remove
      path: /spec/rules/0/forwardTo/1/serviceName
    - op: remove
      path: /spec/rules/0/forwardTo/1/port
    - op: remove
      path: /spec/rules/0/forwardTo/1/weight
      