apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-gateway-api-demo
  name: k8s-gateway-api-demo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-gateway-api-demo
  template:
    metadata:
      labels:
        app: k8s-gateway-api-demo
    spec:
      containers:
      - image: msathetech/k8s-gateway-demo@sha256:fdee187f87a78fdd98cd8365d09a5d06fae9cd6f1e13f66f50b2b11bcf4a69b4
        imagePullPolicy: Always
        name: k8s-gateway-api-demo
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-gateway-api-demo-service
spec:
  selector:
    app: k8s-gateway-api-demo
  ports:
  - port: 8080
    targetPort: 8080

